#!/usr/bin/python3

import zipfile, os

from helpers.log import logger, LOGGER_DEBUG, LOGGER_INFO
from helpers.arguments.parse import parse_args
from helpers.arguments.validate import args_are_valid
import helpers.resource_handler as resource_handler

def build_zips():
    cwd = os.getcwd()
    os.chdir(os.path.join(cwd, "resources", "lambda"))
    with zipfile.ZipFile("CloudCopyCat-Lambda-Function.zip", "w") as z:
        z.write("CloudCopyCat-Lambda-Function.py")
    os.chdir(cwd)
    return


def main():
    args = parse_args()
    if args.debug:
        logger.setLevel(LOGGER_DEBUG)
        logger.debug("Verbose flag provided, printing debug logs")
        logger.debug(f"Received command-line args: {args}")
    else:
        logger.setLevel(LOGGER_INFO)

    if not args_are_valid(args):
        logger.error("Provided arguments are not valid, run again with -v for more details")
        return
    
    # print("Building Lambda zips...")
    # build_zips()

    
    print("Starting CloudCopyCat")
    resource_handler.run(args)
    print("Done")



if __name__ == "__main__":
    main()