## DO NOT EDIT THIS FILE

DEST_BUCKET_POLICY_TEMPLATE = {
    "Version": "2012-10-17",
    "Id": "",
    "Statement": [
        {
            "Sid": "CloudCopyCat-ReplicationDelivery",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*" ## to be filled in at deployment time to avoid cycle
            },
            "Action": [
                "s3:ReplicateObject",
                "s3:ReplicateDelete",
                "s3:PutObject",
                "s3:*"
            ],
            "Resource": "$dest_bucket/object_arn",
            "Condition": {
                "ArnLike": {
                    "aws:PrincipalArn": "" ## to be filled in at deployment time to avoid cycle
                }
            }
        },
        {
            "Sid": "CloudCopyCat-InventoryReportWrites",
            "Effect": "Allow",
            "Principal": {
                "Service": "s3.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "$dest_bucket/object_arn",
            "Condition": {
                "StringEquals": {
                    "aws:SourceAccount": "$src_account",
                    "s3:x-amz-acl": "bucket-owner-full-control"
                },
                "ArnLike": {
                    "aws:SourceArn": "$src_bucket/#all/arn"
                }
            }
        }
    ]
}

STATE_FILE_SCHEMA = {
    "awaiting_inv_report": "$src_bucket/#all/name",
    "awaiting_batch_copy": [],
    "completed": {
        "successful": [],
        "error": []
    }
}
